name: Tests

on:
  pull_request:
    paths-ignore:
    - 'doc/**'
  push:
    branches:
    - main

jobs:
  test:
    env:
      BITRISE_CACHE_ENDPOINT: ${{ vars.BITRISE_CACHE_ENDPOINT }}
      BITRISE_ACCESS_TOKEN: ${{ secrets.BITRISE_ACCESS_TOKEN }}
      BITRISE_WORKSPACE_SLUG: ${{ secrets.BITRISE_WORKSPACE_SLUG }}
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      # - name: Cache
      #   id: cache
      #   uses: actions/cache@v2
      #   with:
      #     path: ~/bazel-disk-cache
      #     key: ${{ runner.os }}-${{ runner.arch }}-bazel-disk-cache
      - name: Setup Linux
        if: runner.os == 'Linux'
        run: |
            export DEBIAN_FRONTEND=noninteractive
            sudo apt-get install -y build-essential git clang libc++-dev
            ./setup_bitrise.sh
      - name: Setup MacOS
        if: runner.os == 'macOS'
        run: |
            ./setup_bitrise.sh
      - name: Setup Windows
        if: runner.os == 'Windows'
        run: |
            .\setup_bitrise.ps1
            [System.IO.File]::WriteAllLines((Join-Path -Path $env:USERPROFILE -ChildPath '.bazelrc'), 'startup --output_user_root=C:/tmp')
      - name: Bazel build
        run: |
            bazelisk build --config bitrise --verbose_failures //...
      - name: Bazel tests
        run: |
            bazelisk test --config bitrise --verbose_failures --show_timestamps --keep_going --test_output=errors //...
      - name: Report disk usage
        if: success() || failure()
        shell: bash
        run: |
            BAZEL_OUTPUT_BASE=$(bazel info --ui_event_filters=-WARNING output_base)
            echo "Bazel output usage statistics"
            du -hs -t 1 $BAZEL_OUTPUT_BASE
            echo "Workspace usage statistics"
            du -hs -t 1 $GITHUB_WORKSPACE

